development:
  adapter: mysql2
  encoding: utf8
  database: channel_datalogging_dev
  username: plaintext_username_here
  password: plaintext_password_here

production:
  adapter: mysql2
  encoding: utf8
  database: channel_datalogging_production
  username: plaintext_username_here
  password: plaintext_password_here
